"""empty message

Revision ID: 486b1b468f00
Revises: a6ea6c69fa2a
Create Date: 2024-12-20 19:08:37.553970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486b1b468f00'
down_revision = 'a6ea6c69fa2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['user_id'], ['id'])

    # ### end Alembic commands ###
