"""empty message

Revision ID: a6ea6c69fa2a
Revises: 
Create Date: 2024-12-19 20:27:33.649810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ea6c69fa2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('piece', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rent_no_set', sa.Integer(), nullable=True),
    sa.Column('rent_color_set', sa.Integer(), nullable=True),
    sa.Column('rent_1_house', sa.Integer(), nullable=True),
    sa.Column('rent_2_house', sa.Integer(), nullable=True),
    sa.Column('rent_3_house', sa.Integer(), nullable=True),
    sa.Column('rent_4_house', sa.Integer(), nullable=True),
    sa.Column('rent_hotel', sa.Integer(), nullable=True),
    sa.Column('building_cost', sa.Integer(), nullable=True),
    sa.Column('mortgage', sa.Integer(), nullable=True),
    sa.Column('unmortgage', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    op.drop_table('players')
    # ### end Alembic commands ###
